-- Define database schema and content in Geoquery

module Geobase
    ( country, states, cities, rivers, borders, highlows, mountains, roads, lakes, 
      State(state_name, state_abbre, state_capital, state_population, state_area, state_number, state_city),
      HighLow(place_state_name, place_state_abbre, highest_point, highest_elevation, lowest_point, lowest_elevation),
      City(city_state_name, city_state_abbre, city_name, city_population),
      Country(country_name, country_population, country_area),
      River(river_name, river_length, river_traverse_states),
      Lake(lake_name, lake_area, lake_traverse_states),
      Mountain(mountain_state_name, mountain_state_abbre, mountain_name, mountain_length),
      Border(border_state_name, border_state_abbre, border_states)
    ) where

-- country(name, area)
type CountryName = String
type CountryPopulation = Double
type CountryArea = Double

data Country = Country {
                  country_name :: String,
                  country_population :: Double,
                  country_area :: Double
                } deriving (Show)

-- state(name  abbreviation  capital  population  area  state_number  city1  city2  city3  city4)
data State = State {
                state_name :: String,
                state_abbre :: String,
                state_capital :: String,
                state_population :: Double,
                state_area :: Double,
                state_number :: Int,
                state_city :: [String]
             } deriving (Show)

-- city(state, state_abreviation, name, population)
data City = City {
                city_state_name :: String,
                city_state_abbre :: String,
                city_name :: String,
                city_population :: Double
            } deriving (Show)

-- river(name, length, [states through which it flows])
data River = River {
                river_name :: String,
                river_length :: Double,
                river_traverse_states :: [String]
            } deriving (Show)

-- border(state, state_abbreviation, [states that border it])
data Border = Border {
                border_state_name :: String,
                border_state_abbre :: String,
                border_states :: [String]
              } deriving (Show)

-- highlow(state, state_abbreviation, highest_point, highest_elevation, lowest_point, lowest_elevation)
data HighLow = HighLow {
                    place_state_name :: String,
                    place_state_abbre :: String,
                    highest_point :: String,
                    highest_elevation :: Double,
                    lowest_point :: String, 
                    lowest_elevation :: Double
                } deriving (Show)

-- mountain(state, state_abbreviation, name, height)
data Mountain = Mountain {
                    mountain_state_name :: String,
                    mountain_state_abbre :: String,
                    mountain_name :: String,
                    mountain_length :: Double
                } deriving (Show)

-- road(number, [states it passes through])
data Road = Road {
                road_number :: String,
                road_cross_states :: [String]
            } deriving (Show)

-- lake(name, area, [states it is in])
data Lake = Lake {
                lake_name :: String,
                lake_area :: Double,
                lake_traverse_states :: [String]
            } deriving (Show)

-- data

country = Country "usa:co" 307890000 9826675

states = [State "alabama:s" "al" "montgomery_al:c" 3894.0e+3 51.7e+3 22 ["birmingham_al:c", "mobile_al:c", "montgomery_al:c", "huntsville_al:c"],
    State "alaska:s" "ak" "juneau_ak:c" 401.8e+3 591.0e+3 49 ["anchorage_ak:c", "fairbanks_ak:c", "juneau_ak:c", "sitka_ak:c"],
    State "arizona:s" "az" "phoenix_az:c" 2718.0e+3 114.0e+3 48 ["phoenix_az:c", "tucson_az:c", "mesa_az:c", "tempe_az:c"],
    State "arkansas:s" "ar" "little_rock_ar:c" 2286.0e+3 53.2e+3 25 ["little_rock_ar:c", "fort_smith_ar:c", "north_little_rock_ar:c", "pine_bluff_ar:c"],
    State "california:s" "ca" "sacramento_ca:c" 23.67e+6 158.0e+3 31 ["los_angeles_ca:c", "san_diego_ca:c", "san_francisco_ca:c", "san_jose_ca:c"],
    State "colorado:s" "co" "denver_co:c" 2889.0e+3 104.0e+3 38 ["denver_co:c", "colorado_springs_co:c", "aurora_co:c", "lakewood_co:c"],
    State "connecticut:s" "ct" "hartford_ct:c" 3107.0e+3 5.02e+3 5 ["bridgeport_ct:c", "hartford_ct:c", "new_haven_ct:c", "waterbury_ct:c"],
    State "delaware:s" "de" "dover_de:c" 594.0e+3 2044 1 ["wilmington_de:c", "newark_de:c", "dover_de:c", "brookside_de:c"],
    State "district_of_columbia:s"  "dc" "washington_dc:c" 638.0e+3 1100 0 ["tenleytown_ dc:c", "washington_dc:c", "georgetown_dc:c", "duval_circle_dc:c"],
    State "florida:s" "fl" "tallahassee_fl:c" 9746.0e+3 68664 27 ["jacksonville_fl:c", "miami_fl:c", "tampa_fl:c", "st._petersburg_fl:c"],
    State "georgia:s" "ga" "atlanta_ga:c" 5463.0e+3 58.9e+3 4 ["atlanta_ga:c", "columbus_ga:c", "savannah_ga:c", "macon_ga:c"],
    State "hawaii:s" "hi" "honolulu_hi:c" 964.0e+3 6471 50 ["honolulu_hi:c", "ewa_hi:c", "koolaupoko_hi:c", "wahiawa_hi:c"],
    State "idaho:s" "id" "boise_id:c" 944.0e+3 83.0e+3 43 ["boise_id:c", "pocatello_id:c", "idaho_falls_id:c", "lewiston_id:c"],
    State "illinois:s" "il" "springfield_il:c" 11.4e+6 56.3e+3 21 ["chicago_il:c", "rockford_il:c", "peoria_il:c", "springfield_il:c"],
    State "indiana:s" "in" "indianapolis_in:c" 5490.0e+3 36.2e+3 19 ["indianapolis_in:c", "fort_wayne_in:c", "gary_in:c", "evansville_in:c"],
    State "iowa:s" "ia" "des_moines_ia:c" 2913.0e+3 56.3e+3 29 ["des_moines_ia:c", "cedar_rapids_ia:c", "davenport_ia:c", "sioux_city_ia:c"],
    State "kansas:s" "ks" "topeka_ks:c" 2364.0e+3 82.3e+3 34 ["wichita_ks:c", "kansas_city_ks:c", "topeka_ks:c", "overland_park_ks:c"],
    State "kentucky:s" "ky" "frankfort_ky:c" 2364.0e+3 82.3e+3 15 ["louisville_ky:c", "lexington_ky:c", "owensboro_ky:c", "covington_ky:c", "frankfort_ky:c"],
    State "louisiana:s" "la" "baton_rouge_la:c" 4206.0e+3 47.7e+3 18 ["new_orleans_la:c", "baton_rouge_la:c", "shreveport_la:c", "metairie_la:c"],
    State "maine:s" "me" "augusta_me:c" 1125.0e+3 33265 23 ["portland_me:c", "lewiston_me:c", "bangor_me:c", "auburn_me:c"],
    State "maryland:s" "md" "annapolis_md:c" 4217.0e+3 10460 7 ["baltimore_md:c", "silver_spring_md:c", "dundalk_md:c", "bethesda_md:c"],
    State "massachusetts:s" "ma" "boston_ma:c" 5737.0e+3 8284 6 ["boston_ma:c", "worcester_ma:c", "springfield_ma:c", "new_bedford_ma:c"],
    State "michigan:s" "mi" "lansing_mi:c" 9262.0e+3 58.5e+3 26 ["detroit_mi:c", "grand_rapids_mi:c", "warren_mi:c", "flint_mi:c"],
    State "minnesota:s" "mn" "st._paul_mn:c" 4076.0e+3 84.4e+3 32 ["minneapolis_mn:c", "st._paul_mn:c", "duluth_mn:c", "bloomington_mn:c"],
    State "mississippi:s" "ms" "jackson_ms:c" 2520.0e+3 47.7e+3 20 ["jackson_ms:c", "biloxi_ms:c", "meridian_ms:c", "hattiesburg_ms:c"],
    State "missouri:s" "mo" "jefferson_city_mo:c" 4916.0e+3 69.7e+3 24 ["st._louis_mo:c", "kansas_city_mo:c", "springfield_mo:c", "independence_mo:c"],
    State "montana:s" "mt" "helena_mt:c" 786.7e+3 147.0e+3 41 ["billings_mt:c", "great_falls_mt:c", "butte_mt:c", "missoula_mt:c"],
    State "nebraska:s" "ne" "lincoln_ne:c" 1569.0e+3 77.3e+3 37 ["omaha_ne:c", "lincoln_ne:c", "grand_island_ne:c", "north_platte_ne:c"],
    State "nevada:s" "nv" "carson_city_nv:c" 800.5e+3 110.5e+3 36 ["las_vegas_nv:c", "reno_nv:c", "sunrise_manor_nv:c", "sparks_nv:c"],
    State "new_hampshire:s" "nh" "concord_nh:c" 920.6e+3 9279 9 ["manchester_nh:c", "nashua_nh:c", "concord_nh:c", "portsmouth_nh:c"],
    State "new_jersey:s" "nj" "trenton_nj:c" 7365.0e+3 7787 3 ["newark_nj:c", "jersey_city_nj:c", "paterson_nj:c", "elizabeth_nj:c"],
    State "new_mexico:s" "nm" "santa_fe_nm:c" 1303.0e+3 121.6e+3 47 ["albuquerque_nm:c", "santa_fe_nm:c", "las_cruces_nm:c", "roswell_nm:c"],
    State "new_york:s" "ny" "albany_ny:c" 17.558e+6 49.1e+3 11 ["new_york_ny:c", "buffalo_ny:c", "rochester_ny:c", "yonkers_ny:c"],
    State "north_carolina:s" "nc" "raleigh_nc:c" 5882.0e+3 52.67e+3 12 ["charlotte_nc:c", "greensboro_nc:c", "raleigh_nc:c", "winston-salem_nc:c"],
    State "north_dakota:s" "nd" "bismarck_nd:c" 652.7e+3 70.7e+3 39 ["fargo_nd:c", "bismarck_nd:c", "grand_forks_nd:c", "minot_nd:c"],
    State "ohio:s" "oh" "columbus_oh:c" 10.8e+6 41.3e+3 17 ["cleveland_oh:c", "columbus_oh:c", "cincinnati_oh:c", "toledo_oh:c"],
    State "oklahoma:s" "ok" "oklahoma_city_ok:c" 3025.0e+3 69.95e+3 46 ["oklahoma_city_ok:c", "tulsa_ok:c", "lawton_ok:c", "norman_ok:c"],
    State "oregon:s" "or" "salem_or:c" 2633.0e+3 97073 33 ["portland_or:c", "eugene_or:c", "salem_or:c", "springfield_or:c"],
    State "pennsylvania:s" "pa" "harrisburg_pa:c" 11.863e+6 45308 2 ["philadelphia_pa:c", "pittsburgh_pa:c", "erie_pa:c", "allentown_pa:c"],
    State "rhode_island:s" "ri" "providence_ri:c" 947.2e+3 1212 13 ["providence_ri:c", "warwick_ri:c", "cranston_ri:c", "pawtucket_ri:c"],
    State "south_carolina:s" "sc" "columbia_sc:c" 3121.8e+3 31.113e+3 8 ["columbia_sc:c", "charleston_sc:c", "north_charleston_sc:c", "greenville_sc:c"],
    State "south_dakota:s" "sd" "pierre_sd:c" 690.767e+3 77116 40 ["sioux_falls_sd:c", "rapid_city_sd:c", "aberdeen_sd:c", "watertown_sd:c"],
    State "tennessee:s" "tn" "nashville_tn:c" 4591.0e+3 42.14e+3 16 ["memphis_tn:c", "nashville_tn:c", "knoxville_tn:c", "chattanooga_tn:c"],
    State "texas:s" "tx" "austin_tx:c" 14.229e+6 266.807e+3 28 ["houston_tx:c", "dallas_tx:c", "san_antonio_tx:c", "el_paso_tx:c"],
    State "utah:s" "ut" "salt_lake_city_ut:c" 1461.0e+3 84.9e+3 45 ["salt_lake_city_ut:c", "provo_ut:c", "west_valley_ut:c", "ogden_ut:c"],
    State "vermont:s" "vt" "montpelier_vt:c" 511.5e+3 9614 14 ["burlington_vt:c", "rutland_vt:c", "bennington_vt:c", "essex_vt:c"],
    State "virginia:s" "va" "richmond_va:c" 5346.8e+3 40.76e+3 10 ["norfolk_va:c", "virginia_beach_va:c", "richmond_va:c", "arlington_va:c"],
    State "washington:s" "wa" "olympia_wa:c" 41.132e+5 68.139e+3 42 ["seattle_wa:c", "spokane_wa:c", "tacoma_wa:c", "bellevue_wa:c"],
    State "west_virginia:s" "wv" "charleston_wv:c" 1.95e+6 24.2e+3 35 ["charleston_wv:c", "huntington_wv:c", "wheeling_wv:c", "parkersburg_wv:c"],
    State "wisconsin:s" "wi" "madison_wi:c" 4.7e+6 56153 30 ["milwaukee_wi:c", "madison_wi:c", "green_bay_wi:c", "racine_wi:c"],
    State "wyoming:s" "wy" "cheyenne_wy:c" 469.557e+3 97.809e+3 44 ["casper_wy:c", "cheyenne_wy:c", "laramie_wy:c", "rock_springs_wy:c"]]


cities = [City "alabama:s" "al" "birmingham_al:c" 284413,
    City "alabama:s" "al" "mobile_al:c" 200452,
    City "alabama:s" "al" "montgomery_al:c" 177857,
    City "alabama:s" "al" "huntsville_al:c" 142513,
    City "alabama:s" "al" "tuscaloosa_al:c" 75143,
    City "alaska:s" "ak" "anchorage_ak:c" 174431,
    City "arizona:s" "az" "phoenix_az:c" 789704,
    City "arizona:s" "az" "tucson_az:c" 330537,
    City "arizona:s" "az" "mesa_az:c" 152453,
    City "arizona:s" "az" "tempe_az:c" 106919,
    City "arizona:s" "az" "glendale_az:c" 96988,
    City "arizona:s" "az" "scottsdale_az:c" 88622,
    City "arkansas:s" "ar" "little_rock_ar:c" 158915,
    City "arkansas:s" "ar" "fort_smith_ar:c" 71384,
    City "arkansas:s" "ar" "north_little_rock_ar:c" 64388,
    City "california:s" "ca" "los_angeles_ca:c" 2966850,
    City "california:s" "ca" "san_diego_ca:c" 875538,
    City "california:s" "ca" "san_francisco_ca:c" 678974,
    City "california:s" "ca" "san_jose_ca:c" 629442,
    City "california:s" "ca" "long_beach_ca:c" 361334,
    City "california:s" "ca" "oakland_ca:c" 339337,
    City "california:s" "ca" "sacramento_ca:c" 275741,
    City "california:s" "ca" "anaheim_ca:c" 219311,
    City "california:s" "ca" "fresno_ca:c" 218202,
    City "california:s" "ca" "santa_ana_ca:c" 203713,
    City "california:s" "ca" "riverside_ca:c" 170876,
    City "california:s" "ca" "huntington_beach_ca:c" 170505,
    City "california:s" "ca" "stockton_ca:c" 149779,
    City "california:s" "ca" "glendale_ca:c" 139060,
    City "california:s" "ca" "fremont_ca:c" 131945,
    City "california:s" "ca" "torrance_ca:c" 131497,
    City "california:s" "ca" "garden_grove_ca:c" 123351,
    City "california:s" "ca" "san_bernardino_ca:c" 118794,
    City "california:s" "ca" "pasadena_ca:c" 118072,
    City "california:s" "ca" "east_los_angeles_ca:c" 110017,
    City "california:s" "ca" "oxnard_ca:c" 108195,
    City "california:s" "ca" "modesto_ca:c" 106963,
    City "california:s" "ca" "sunnyvale_ca:c" 106618,
    City "california:s" "ca" "bakersfield_ca:c" 105611,
    City "california:s" "ca" "concord_ca:c" 103763,
    City "california:s" "ca" "berkeley_ca:c" 103328,
    City "california:s" "ca" "fullerton_ca:c" 102246,
    City "california:s" "ca" "inglewood_ca:c" 94162,
    City "california:s" "ca" "hayward_ca:c" 93585,
    City "california:s" "ca" "pomona_ca:c" 92742,
    City "california:s" "ca" "orange_ca:c" 91450,
    City "california:s" "ca" "ontario_ca:c" 88820,
    City "california:s" "ca" "santa_monica_ca:c" 88314,
    City "california:s" "ca" "santa_clara_ca:c" 87700,
    City "california:s" "ca" "citrus_heights_ca:c" 85911,
    City "california:s" "ca" "norwalk_ca:c" 84901,
    City "california:s" "ca" "burbank_ca:c" 84625,
    City "california:s" "ca" "chula_vista_ca:c" 83927,
    City "california:s" "ca" "santa_rosa_ca:c" 83205,
    City "california:s" "ca" "downey_ca:c" 82602,
    City "california:s" "ca" "costa_mesa_ca:c" 82291,
    City "california:s" "ca" "compton_ca:c" 81230,
    City "california:s" "ca" "carson_ca:c" 81221,
    City "california:s" "ca" "salinas_ca:c" 80479,
    City "california:s" "ca" "west_covina_ca:c" 80292,
    City "california:s" "ca" "vallejo_ca:c" 80188,
    City "california:s" "ca" "el_monte_ca:c" 79494,
    City "california:s" "ca" "daly_city_ca:c" 78519,
    City "california:s" "ca" "thousand_oaks_ca:c" 77797,
    City "california:s" "ca" "san_mateo_ca:c" 77640,
    City "california:s" "ca" "simi_valley_ca:c" 77500,
    City "california:s" "ca" "oceanside_ca:c" 76698,
    City "california:s" "ca" "richmond_ca:c" 74676,
    City "california:s" "ca" "lakewood_ca:c" 74654,
    City "california:s" "ca" "santa_barbara_ca:c" 74542,
    City "california:s" "ca" "el_cajon_ca:c" 73892,
    City "california:s" "ca" "ventura_ca:c" 73774,
    City "california:s" "ca" "westminster_ca:c" 71133,
    City "california:s" "ca" "whittier_ca:c" 68558,
    City "california:s" "ca" "south_gate_ca:c" 66784,
    City "california:s" "ca" "alhambra_ca:c" 64767,
    City "california:s" "ca" "buena_park_ca:c" 64165,
    City "california:s" "ca" "san_leandro_ca:c" 63952,
    City "california:s" "ca" "alameda_ca:c" 63852,
    City "california:s" "ca" "newport_beach_ca:c" 63475,
    City "california:s" "ca" "escondido_ca:c" 62480,
    City "california:s" "ca" "irvine_ca:c" 62134,
    City "california:s" "ca" "mountain_view_ca:c" 58655,
    City "california:s" "ca" "fairfield_ca:c" 58099,
    City "california:s" "ca" "redondo_beach_ca:c" 57102,
    City "california:s" "ca" "scotts_valley_ca:c" 6037,
    City "colorado:s" "co" "denver_co:c" 492365,
    City "colorado:s" "co" "colorado_springs_co:c" 215150,
    City "colorado:s" "co" "aurora_co:c" 158588,
    City "colorado:s" "co" "lakewood_co:c" 113808,
    City "colorado:s" "co" "pueblo_co:c" 101686,
    City "colorado:s" "co" "arvada_co:c" 84576,
    City "colorado:s" "co" "boulder_co:c" 76685,
    City "colorado:s" "co" "fort_collins_co:c" 64632,
    City "connecticut:s" "ct" "bridgeport_ct:c" 142546,
    City "connecticut:s" "ct" "hartford_ct:c" 136392,
    City "connecticut:s" "ct" "new_haven_ct:c" 126089,
    City "connecticut:s" "ct" "waterbury_ct:c" 103266,
    City "connecticut:s" "ct" "stamford_ct:c" 102466,
    City "connecticut:s" "ct" "norwalk_ct:c" 77767,
    City "connecticut:s" "ct" "new_britain_ct:c" 73840,
    City "connecticut:s" "ct" "west_hartford_ct:c" 61301,
    City "connecticut:s" "ct" "danbury_ct:c" 60470,
    City "connecticut:s" "ct" "greenwich_ct:c" 59578,
    City "connecticut:s" "ct" "bristol_ct:c" 57370,
    City "connecticut:s" "ct" "meriden_ct:c" 57118,
    City "delaware:s" "de" "wilmington_de:c" 70195,
    City "district_of_columbia:s" "dc" "washington_dc:c" 638333,
    City "florida:s" "fl" "jacksonville_fl:c" 540920,
    City "florida:s" "fl" "miami_fl:c" 346865,
    City "florida:s" "fl" "tampa_fl:c" 271523,
    City "florida:s" "fl" "st._petersburg_fl:c" 238647,
    City "florida:s" "fl" "fort_lauderdale_fl:c" 153256,
    City "florida:s" "fl" "orlando_fl:c" 128394,
    City "florida:s" "fl" "hollywood_fl:c" 117188,
    City "florida:s" "fl" "miami_beach_fl:c" 96298,
    City "florida:s" "fl" "clearwater_fl:c" 85450,
    City "florida:s" "fl" "tallahassee_fl:c" 81548,
    City "florida:s" "fl" "gainesville_fl:c" 81371,
    City "florida:s" "fl" "kendall_fl:c" 73758,
    City "florida:s" "fl" "west_palm_beach_fl:c" 62530,
    City "florida:s" "fl" "largo_fl:c" 58977,
    City "florida:s" "fl" "pensacola_fl:c" 57619,
    City "georgia:s" "ga" "atlanta_ga:c" 425022,
    City "georgia:s" "ga" "columbus_ga:c" 169441,
    City "georgia:s" "ga" "savannah_ga:c" 141654,
    City "georgia:s" "ga" "macon_ga:c" 116860,
    City "georgia:s" "ga" "albany_ga:c" 74425,
    City "hawaii:s" "hi" "honolulu_hi:c" 762874,
    City "hawaii:s" "hi" "ewa_hi:c" 190037,
    City "hawaii:s" "hi" "koolaupoko_hi:c" 109373,
    City "idaho:s" "id" "boise_id:c" 102249,
    City "illinois:s" "il" "chicago_il:c" 3005172,
    City "illinois:s" "il" "rockford_il:c" 139712,
    City "illinois:s" "il" "peoria_il:c" 124160,
    City "illinois:s" "il" "springfield_il:c" 100054,
    City "illinois:s" "il" "decatur_il:c" 93939,
    City "illinois:s" "il" "aurora_il:c" 81293,
    City "illinois:s" "il" "joliet_il:c" 77956,
    City "illinois:s" "il" "evanston_il:c" 73706,
    City "illinois:s" "il" "waukegan_il:c" 67653,
    City "illinois:s" "il" "arlington_heights_il:c" 66116,
    City "illinois:s" "il" "elgin_il:c" 63668,
    City "illinois:s" "il" "cicero_il:c" 61232,
    City "illinois:s" "il" "oak_lawn_il:c" 60590,
    City "illinois:s" "il" "skokie_il:c" 60278,
    City "illinois:s" "il" "champaign_il:c" 58267,
    City "indiana:s" "in" "indianapolis_in:c" 700807,
    City "indiana:s" "in" "fort_wayne_in:c" 172196,
    City "indiana:s" "in" "gary_in:c" 151968,
    City "indiana:s" "in" "evansville_in:c" 130496,
    City "indiana:s" "in" "south_bend_in:c" 109727,
    City "indiana:s" "in" "hammond_in:c" 93714,
    City "indiana:s" "in" "muncie_in:c" 77216,
    City "indiana:s" "in" "anderson_in:c" 64695,
    City "indiana:s" "in" "terre_haute_in:c" 61125,
    City "iowa:s" "ia" "des_moines_ia:c" 191003,
    City "iowa:s" "ia" "cedar_rapids_ia:c" 110243,
    City "iowa:s" "ia" "davenport_ia:c" 103254,
    City "iowa:s" "ia" "sioux_city_ia:c" 82003,
    City "iowa:s" "ia" "waterloo_ia:c" 75985,
    City "iowa:s" "ia" "dubuque_ia:c" 62321,
    City "kansas:s" "ks" "wichita_ks:c" 279212,
    City "kansas:s" "ks" "kansas_city_ks:c" 161148,
    City "kansas:s" "ks" "topeka_ks:c" 118690,
    City "kansas:s" "ks" "overland_park_ks:c" 81784,
    City "kentucky:s" "ky" "louisville_ky:c" 298451,
    City "kentucky:s" "ky" "lexington_ky:c" 204165,
    City "louisiana:s" "la" "new_orleans_la:c" 557515,
    City "louisiana:s" "la" "baton_rouge_la:c" 219419,
    City "louisiana:s" "la" "shreveport_la:c" 205820,
    City "louisiana:s" "la" "metairie_la:c" 164160,
    City "louisiana:s" "la" "lafayette_la:c" 80584,
    City "louisiana:s" "la" "lake_charles_la:c" 75051,
    City "louisiana:s" "la" "kenner_la:c" 66382,
    City "louisiana:s" "la" "monroe_la:c" 57597,
    City "maine:s" "me" "portland_me:c" 61572,
    City "maryland:s" "md" "baltimore_md:c" 786775,
    City "maryland:s" "md" "silver_spring_md:c" 72893,
    City "maryland:s" "md" "dundalk_md:c" 71293,
    City "maryland:s" "md" "bethesda_md:c" 63022,
    City "massachusetts:s" "ma" "boston_ma:c" 562994,
    City "massachusetts:s" "ma" "worcester_ma:c" 161799,
    City "massachusetts:s" "ma" "springfield_ma:c" 152319,
    City "massachusetts:s" "ma" "new_bedford_ma:c" 98478,
    City "massachusetts:s" "ma" "cambridge_ma:c" 95322,
    City "massachusetts:s" "ma" "brockton_ma:c" 95172,
    City "massachusetts:s" "ma" "fall_river_ma:c" 92574,
    City "massachusetts:s" "ma" "lowell_ma:c" 92418,
    City "massachusetts:s" "ma" "quincy_ma:c" 84743,
    City "massachusetts:s" "ma" "newton_ma:c" 83622,
    City "massachusetts:s" "ma" "lynn_ma:c" 78471,
    City "massachusetts:s" "ma" "somerville_ma:c" 77372,
    City "massachusetts:s" "ma" "framingham_ma:c" 65113,
    City "massachusetts:s" "ma" "lawrence_ma:c" 63175,
    City "massachusetts:s" "ma" "waltham_ma:c" 58200,
    City "massachusetts:s" "ma" "medford_ma:c" 58076,
    City "michigan:s" "mi" "detroit_mi:c" 1203339,
    City "michigan:s" "mi" "grand_rapids_mi:c" 181843,
    City "michigan:s" "mi" "warren_mi:c" 161134,
    City "michigan:s" "mi" "flint_mi:c" 159611,
    City "michigan:s" "mi" "lansing_mi:c" 130414,
    City "michigan:s" "mi" "sterling_heights_mi:c" 108999,
    City "michigan:s" "mi" "ann_arbor_mi:c" 107969,
    City "michigan:s" "mi" "livonia_mi:c" 104814,
    City "michigan:s" "mi" "dearborn_mi:c" 90660,
    City "michigan:s" "mi" "westland_mi:c" 84603,
    City "michigan:s" "mi" "kalamazoo_mi:c" 79722,
    City "michigan:s" "mi" "taylor_mi:c" 77568,
    City "michigan:s" "mi" "saginaw_mi:c" 77508,
    City "michigan:s" "mi" "pontiac_mi:c" 76715,
    City "michigan:s" "mi" "st._clair_shores_mi:c" 76210,
    City "michigan:s" "mi" "southfield_mi:c" 75568,
    City "michigan:s" "mi" "clinton_mi:c" 72400,
    City "michigan:s" "mi" "royal_oak_mi:c" 70893,
    City "michigan:s" "mi" "dearborn_heights_mi:c" 67706,
    City "michigan:s" "mi" "troy_mi:c" 67102,
    City "michigan:s" "mi" "waterford_mi:c" 64250,
    City "michigan:s" "mi" "wyoming_mi:c" 59616,
    City "michigan:s" "mi" "redford_mi:c" 58441,
    City "michigan:s" "mi" "farmington_hills_mi:c" 58056,
    City "minnesota:s" "mn" "minneapolis_mn:c" 370951,
    City "minnesota:s" "mn" "st._paul_mn:c" 270230,
    City "minnesota:s" "mn" "duluth_mn:c" 92811,
    City "minnesota:s" "mn" "bloomington_mn:c" 81831,
    City "minnesota:s" "mn" "rochester_mn:c" 57906,
    City "mississippi:s" "ms" "jackson_ms:c" 202895,
    City "missouri:s" "mo" "st._louis_mo:c" 453085,
    City "missouri:s" "mo" "kansas_city_mo:c" 448159,
    City "missouri:s" "mo" "springfield_mo:c" 133116,
    City "missouri:s" "mo" "independence_mo:c" 111797,
    City "missouri:s" "mo" "st._joseph_mo:c" 76691,
    City "missouri:s" "mo" "columbia_mo:c" 62061,
    City "montana:s" "mt" "billings_mt:c" 66842,
    City "montana:s" "mt" "great_falls_mt:c" 56725,
    City "nebraska:s" "ne" "omaha_ne:c" 314255,
    City "nebraska:s" "ne" "lincoln_ne:c" 171932,
    City "nevada:s" "nv" "las_vegas_nv:c" 164674,
    City "nevada:s" "nv" "reno_nv:c" 100756,
    City "new_hampshire:s" "nh" "manchester_nh:c" 90936,
    City "new_hampshire:s" "nh" "nashua_nh:c" 67865,
    City "new_jersey:s" "nj" "newark_nj:c" 329248,
    City "new_jersey:s" "nj" "jersey_city_nj:c" 223532,
    City "new_jersey:s" "nj" "paterson_nj:c" 137970,
    City "new_jersey:s" "nj" "elizabeth_nj:c" 106201,
    City "new_jersey:s" "nj" "trenton_nj:c" 92124,
    City "new_jersey:s" "nj" "woodbridge_nj:c" 90074,
    City "new_jersey:s" "nj" "camden_nj:c" 84910,
    City "new_jersey:s" "nj" "east_orange_nj:c" 77878,
    City "new_jersey:s" "nj" "clifton_nj:c" 74388,
    City "new_jersey:s" "nj" "edison_nj:c" 70193,
    City "new_jersey:s" "nj" "cherry_hill_nj:c" 68785,
    City "new_jersey:s" "nj" "bayonne_nj:c" 65047,
    City "new_jersey:s" "nj" "middletown_nj:c" 61615,
    City "new_jersey:s" "nj" "irvington_nj:c" 61493,
    City "new_mexico:s" "nm" "albuquerque_nm:c" 331767,
    City "new_york:s" "ny" "new_york_ny:c" 7071639,
    City "new_york:s" "ny" "buffalo_ny:c" 357870,
    City "new_york:s" "ny" "rochester_ny:c" 241741,
    City "new_york:s" "ny" "yonkers_ny:c" 195351,
    City "new_york:s" "ny" "syracuse_ny:c" 170105,
    City "new_york:s" "ny" "albany_ny:c" 101727,
    City "new_york:s" "ny" "cheektowaga_ny:c" 92145,
    City "new_york:s" "ny" "utica_ny:c" 75632,
    City "new_york:s" "ny" "niagara_falls_ny:c" 71384,
    City "new_york:s" "ny" "new_rochelle_ny:c" 70794,
    City "new_york:s" "ny" "schenectady_ny:c" 67972,
    City "new_york:s" "ny" "mount_vernon_ny:c" 66713,
    City "new_york:s" "ny" "irondequoit_ny:c" 57648,
    City "new_york:s" "ny" "levittown_ny:c" 57045,
    City "north_carolina:s" "nc" "charlotte_nc:c" 314447,
    City "north_carolina:s" "nc" "greensboro_nc:c" 155642,
    City "north_carolina:s" "nc" "raleigh_nc:c" 149771,
    City "north_carolina:s" "nc" "winston-salem_nc:c" 131885,
    City "north_carolina:s" "nc" "durham_nc:c" 100538,
    City "north_carolina:s" "nc" "high_point_nc:c" 64107,
    City "north_carolina:s" "nc" "fayetteville_nc:c" 59507,
    City "north_dakota:s" "nd" "fargo_nd:c" 61308,
    City "ohio:s" "oh" "cleveland_oh:c" 573822,
    City "ohio:s" "oh" "columbus_oh:c" 564871,
    City "ohio:s" "oh" "cincinnati_oh:c" 385457,
    City "ohio:s" "oh" "toledo_oh:c" 354635,
    City "ohio:s" "oh" "akron_oh:c" 237177,
    City "ohio:s" "oh" "dayton_oh:c" 203371,
    City "ohio:s" "oh" "youngstown_oh:c" 115436,
    City "ohio:s" "oh" "canton_oh:c" 93077,
    City "ohio:s" "oh" "parma_oh:c" 92548,
    City "ohio:s" "oh" "lorain_oh:c" 75416,
    City "ohio:s" "oh" "springfield_oh:c" 72563,
    City "ohio:s" "oh" "hamilton_oh:c" 63189,
    City "ohio:s" "oh" "lakewood_oh:c" 61963,
    City "ohio:s" "oh" "kettering_oh:c" 61186,
    City "ohio:s" "oh" "euclid_oh:c" 59999,
    City "ohio:s" "oh" "elyria_oh:c" 57504,
    City "oklahoma:s" "ok" "oklahoma_city_ok:c" 403213,
    City "oklahoma:s" "ok" "tulsa_ok:c" 360919,
    City "oklahoma:s" "ok" "lawton_ok:c" 80054,
    City "oklahoma:s" "ok" "norman_ok:c" 68020,
    City "oregon:s" "or" "portland_or:c" 366383,
    City "oregon:s" "or" "eugene_or:c" 105664,
    City "oregon:s" "or" "salem_or:c" 89233,
    City "pennsylvania:s" "pa" "philadelphia_pa:c" 1688210,
    City "pennsylvania:s" "pa" "pittsburgh_pa:c" 423938,
    City "pennsylvania:s" "pa" "erie_pa:c" 119123,
    City "pennsylvania:s" "pa" "allentown_pa:c" 103758,
    City "pennsylvania:s" "pa" "scranton_pa:c" 88117,
    City "pennsylvania:s" "pa" "upper_darby_pa:c" 84054,
    City "pennsylvania:s" "pa" "reading_pa:c" 78686,
    City "pennsylvania:s" "pa" "bethlehem_pa:c" 70419,
    City "pennsylvania:s" "pa" "lower_merion_pa:c" 59651,
    City "pennsylvania:s" "pa" "abingdon_pa:c" 59084,
    City "pennsylvania:s" "pa" "bristol_township_pa:c" 58733,
    City "pennsylvania:s" "pa" "penn_hills_pa:c" 57632,
    City "pennsylvania:s" "pa" "altoona_pa:c" 57078,
    City "rhode_island:s" "ri" "providence_ri:c" 156804,
    City "rhode_island:s" "ri" "warwick_ri:c" 87123,
    City "rhode_island:s" "ri" "cranston_ri:c" 71992,
    City "rhode_island:s" "ri" "pawtucket_ri:c" 71204,
    City "south_carolina:s" "sc" "columbia_sc:c" 101229,
    City "south_carolina:s" "sc" "charleston_sc:c" 69855,
    City "south_carolina:s" "sc" "north_charleston_sc:c" 62504,
    City "south_carolina:s" "sc" "greenville_sc:c" 58242,
    City "south_dakota:s" "sd" "sioux_falls_sd:c" 81343,
    City "tennessee:s" "tn" "memphis_tn:c" 646356,
    City "tennessee:s" "tn" "nashville_tn:c" 455651,
    City "tennessee:s" "tn" "knoxville_tn:c" 175030,
    City "tennessee:s" "tn" "chattanooga_tn:c" 169728,
    City "texas:s" "tx" "houston_tx:c" 1595138,
    City "texas:s" "tx" "dallas_tx:c" 904078,
    City "texas:s" "tx" "san_antonio_tx:c" 785880,
    City "texas:s" "tx" "el_paso_tx:c" 425259,
    City "texas:s" "tx" "fort_worth_tx:c" 385164,
    City "texas:s" "tx" "austin_tx:c" 345496,
    City "texas:s" "tx" "corpus_christi_tx:c" 231999,
    City "texas:s" "tx" "lubbock_tx:c" 173979,
    City "texas:s" "tx" "arlington_tx:c" 160123,
    City "texas:s" "tx" "amarillo_tx:c" 149230,
    City "texas:s" "tx" "garland_tx:c" 138857,
    City "texas:s" "tx" "beaumont_tx:c" 118102,
    City "texas:s" "tx" "pasadena_tx:c" 112560,
    City "texas:s" "tx" "irving_tx:c" 109943,
    City "texas:s" "tx" "waco_tx:c" 101261,
    City "texas:s" "tx" "abilene_tx:c" 98315,
    City "texas:s" "tx" "wichita_falls_tx:c" 94201,
    City "texas:s" "tx" "laredo_tx:c" 91449,
    City "texas:s" "tx" "odessa_tx:c" 90027,
    City "texas:s" "tx" "brownsville_tx:c" 84997,
    City "texas:s" "tx" "san_angelo_tx:c" 73240,
    City "texas:s" "tx" "richardson_tx:c" 72496,
    City "texas:s" "tx" "plano_tx:c" 72331,
    City "texas:s" "tx" "grand_prairie_tx:c" 71462,
    City "texas:s" "tx" "midland_tx:c" 70525,
    City "texas:s" "tx" "tyler_tx:c" 70508,
    City "texas:s" "tx" "mesquite_tx:c" 67053,
    City "texas:s" "tx" "mcallen_tx:c" 67042,
    City "texas:s" "tx" "longview_tx:c" 62762,
    City "texas:s" "tx" "port_arthur_tx:c" 61195,
    City "utah:s" "ut" "salt_lake_city_ut:c" 163034,
    City "utah:s" "ut" "provo_ut:c" 74111,
    City "utah:s" "ut" "west_valley_ut:c" 72299,
    City "utah:s" "ut" "ogden_ut:c" 64407,
    City "virginia:s" "va" "norfolk_va:c" 266979,
    City "virginia:s" "va" "virginia_beach_va:c" 262199,
    City "virginia:s" "va" "richmond_va:c" 219214,
    City "virginia:s" "va" "arlington_va:c" 152599,
    City "virginia:s" "va" "newport_news_va:c" 144903,
    City "virginia:s" "va" "hampton_va:c" 122617,
    City "virginia:s" "va" "chesapeake_va:c" 114226,
    City "virginia:s" "va" "portsmouth_va:c" 104577,
    City "virginia:s" "va" "alexandria_va:c" 103217,
    City "virginia:s" "va" "roanoke_va:c" 100427,
    City "virginia:s" "va" "lynchburg_va:c" 66743,
    City "washington:s" "wa" "seattle_wa:c" 493846,
    City "washington:s" "wa" "spokane_wa:c" 171300,
    City "washington:s" "wa" "tacoma_wa:c" 158501,
    City "washington:s" "wa" "bellevue_wa:c" 73903,
    City "west_virginia:s" "wv" "charleston_wv:c" 63968,
    City "west_virginia:s" "wv" "huntington_wv:c" 63684,
    City "wisconsin:s" "wi" "milwaukee_wi:c" 636212,
    City "wisconsin:s" "wi" "madison_wi:c" 170616,
    City "wisconsin:s" "wi" "green_bay_wi:c" 87899,
    City "wisconsin:s" "wi" "racine_wi:c" 85725,
    City "wisconsin:s" "wi" "kenosha_wi:c" 77685,
    City "wisconsin:s" "wi" "west_allis_wi:c" 63982,
    City "wisconsin:s" "wi" "appleton_wi:c" 58913,
    City "wyoming:s" "wy" "casper_wy:c" 51016]

rivers = [River "mississippi_river:r" 3778 ["minnesota:s", "wisconsin:s", "iowa:s", "illinois:s", "missouri:s", "kentucky:s", "tennessee:s", "arkansas:s", "mississippi:s", "louisiana:s"],
    River "missouri_river:r" 3968 ["montana:s", "north_dakota:s", "south_dakota:s", "iowa:s", "nebraska:s", "missouri:s"],
    River "colorado_river:r" 2333 ["colorado:s", "utah:s", "arizona:s", "nevada:s", "california:s"],
    River "ohio_river:r" 1569 ["pennsylvania:s", "west_virginia:s", "kentucky:s", "indiana:s", "illinois:s", "illinois:s", "ohio:s"],
    River "red_river:r" 1638 ["new_mexico:s", "texas:s", "oklahoma:s", "arkansas:s", "arkansas:s", "louisiana:s"],
    River "arkansas_river:r" 2333 ["colorado:s", "kansas:s", "oklahoma:s", "arkansas:s"],
    River "canadian_river:r" 1458 ["colorado:s", "new_mexico:s", "texas:s", "oklahoma:s"],
    River "connecticut_river:r" 655 ["new_hampshire:s", "vermont:s", "massachusetts:s", "connecticut:s"],
    River "delaware_river:r" 451 ["new_york:s", "pennsylvania:s", "new_jersey:s", "delaware:s"],
    River "little_missouri_river:r" 901 ["wyoming:s", "montana:s", "south_dakota:s", "north_dakota:s"],
    River "snake_river:r" 1670 ["wyoming:s", "idaho:s", "oregon:s", "washington:s", "washington:s"],
    River "chattahoochee_river:r" 702 ["georgia:s", "georgia:s", "florida:s"],
    River "cimarron_river:r" 965 ["new_mexico:s", "kansas:s", "oklahoma:s"],
    River "green_river:r" 1175 ["wyoming:s", "utah:s", "colorado:s", "utah:s"],
    River "north_platte_river:r" 1094 ["colorado:s", "wyoming:s", "nebraska:s"],
    River "potomac_river:r" 462 ["west_virginia:s", "maryland:s", "virginia:s", "district_of_columbia:s"],
    River "republican_river:r" 679 ["colorado:s", "nebraska:s", "kansas:s"],
    River "rio_grande_river:r" 3033 ["colorado:s", "new_mexico:s", "texas:s"],
    River "san_juan_river:r" 579 ["colorado:s", "new_mexico:s", "colorado:s", "utah:s"],
    River "tennessee_river:r" 1049 ["tennessee:s", "alabama:s", "tennessee:s", "kentucky:s"],
    River "wabash_river:r" 764 ["ohio:s", "indiana:s", "illinois:s"],
    River "yellowstone_river:r" 1080 ["wyoming:s", "montana:s", "north_dakota:s"],
    River "allegheny_river:r" 523 ["pennsylvania:s", "new_york:s", "pennsylvania:s"],
    River "bighorn_river:r" 541 ["wyoming:s", "montana:s"],
    River "cheyenne_river:r" 848 ["wyoming:s", "north_dakota:s"],
    River "clark_fork_river:r" 483 ["montana:s", "idaho:s"],
    River "columbia_river:r" 1953 ["washington:s", "oregon:s"],
    River "cumberland_river:r" 1105 ["kentucky:s", "tennessee:s", "kentucky:s"],
    River "dakota_river:r" 1142 ["north_dakota:s", "south_dakota:s"],
    River "gila_river:r" 805 ["new_mexico:s", "arizona:s"],
    River "hudson_river:r" 492 ["new_york:s", "new_jersey:s"],
    River "neosho_river:r" 740 ["kansas:s", "oklahoma:s"],
    River "niobrara_river:r" 693 ["wyoming:s", "nebraska:s"],
    River "ouachita_river:r" 973 ["arkansas:s", "louisiana:s"],
    River "pearl_river:r" 788 ["michigan:s", "louisiana:s"],
    River "pecos_river:r" 805 ["new_mexico:s", "texas:s"],
    River "powder_river:r" 603 ["wyoming:s", "montana:s"],
    River "roanoke_river:r" 660 ["virginia:s", "north_carolina:s"],
    River "rock_river:r" 459 ["wisconsin:s", "illinois:s"],
    River "smoky_hill_river:r" 869 ["colorado:s", "kansas:s"],
    River "south_platte_river:r" 682 ["colorado:s", "nebraska:s"],
    River "st._francis_river:r" 684 ["missouri:s", "arkansas:s"],
    River "tombigbee_river:r" 658 ["mississippi:s", "alabama:s"],
    River "washita_river:r" 805 ["texas:s", "oklahoma:s"],
    River "wateree_catawba_river:r" 636 ["north_carolina:s", "south_carolina:s"],
    River "white_river:r" 1110 ["arkansas:s", "missouri:s", "arkansas:s"]]


borders = [Border "alabama:s" "al" ["tennessee:s", "georgia:s", "florida:s", "mississippi:s"],
    Border "alaska:s" "ak" [],
    Border "arizona:s" "az" ["utah:s", "colorado:s", "new_mexico:s", "california:s", "nevada:s"],
    Border "arkansas:s" "ar" ["missouri:s", "tennessee:s", "mississippi:s", "louisiana:s", "texas:s", "oklahoma:s"],
    Border "california:s" "ca" ["oregon:s", "nevada:s", "arizona:s"],
    Border "colorado:s" "co" ["nebraska:s", "kansas:s", "oklahoma:s", "new_mexico:s", "arizona:s", "utah:s", "wyoming:s"],
    Border "connecticut:s" "ct" ["massachusetts:s", "rhode_island:s", "new_york:s"],
    Border "delaware:s" "de" ["pennsylvania:s", "new_jersey:s", "maryland:s"],
    Border "district_of_columbia:s" "dc" ["maryland:s", "virginia:s"],
    Border "florida:s" "fl" ["georgia:s", "alabama:s"],
    Border "georgia:s" "ga" ["north_carolina:s", "south_carolina:s", "florida:s", "alabama:s", "tennessee:s"],
    Border "hawaii:s" "hi" [],
    Border "idaho:s" "id" ["montana:s", "wyoming:s", "utah:s", "nevada:s", "oregon:s", "washington:s"],
    Border "illinois:s" "il" ["wisconsin:s", "indiana:s", "kentucky:s", "missouri:s", "iowa:s"],
    Border "indiana:s" "in" ["michigan:s", "ohio:s", "kentucky:s", "illinois:s"],
    Border "iowa:s" "ia" ["minnesota:s", "wisconsin:s", "illinois:s", "missouri:s", "nebraska:s", "south_dakota:s"],
    Border "kansas:s" "ks" ["nebraska:s", "missouri:s", "oklahoma:s", "colorado:s"],
    Border "kentucky:s" "ky" ["indiana:s", "ohio:s", "west_virginia:s", "virginia:s", "tennessee:s", "missouri:s", "illinois:s"],
    Border "louisiana:s" "la" ["arkansas:s", "mississippi:s", "texas:s"],
    Border "maine:s" "me" ["new_hampshire:s"],
    Border "maryland:s" "md" ["pennsylvania:s", "delaware:s", "virginia:s", "district_of_columbia:s", "west_virginia:s"],
    Border "massachusetts:s" "ma" ["new_hampshire:s", "rhode_island:s", "connecticut:s", "new_york:s", "vermont:s"],
    Border "michigan:s" "mi" ["ohio:s", "indiana:s", "wisconsin:s"],
    Border "minnesota:s" "mn" ["wisconsin:s", "iowa:s", "south_dakota:s", "north_dakota:s"],
    Border "mississippi:s" "ms" ["tennessee:s", "alabama:s", "louisiana:s", "arkansas:s"],
    Border "missouri:s" "mo" ["iowa:s", "illinois:s", "kentucky:s", "tennessee:s", "arkansas:s", "oklahoma:s", "kansas:s", "nebraska:s"],
    Border "montana:s" "mt" ["north_dakota:s", "south_dakota:s", "wyoming:s", "idaho:s"],
    Border "nebraska:s" "ne" ["south_dakota:s", "iowa:s", "missouri:s", "kansas:s", "colorado:s", "wyoming:s"],
    Border "nevada:s" "nv" ["idaho:s", "utah:s", "arizona:s", "california:s", "oregon:s"],
    Border "new_hampshire:s" "nh" ["maine:s", "massachusetts:s", "vermont:s"],
    Border "new_jersey:s" "nj" ["new_york:s", "delaware:s", "pennsylvania:s"],
    Border "new_mexico:s" "nm" ["colorado:s", "oklahoma:s", "texas:s", "arizona:s", "utah:s"],
    Border "new_york:s" "ny" ["vermont:s", "massachusetts:s", "connecticut:s", "new_jersey:s", "pennsylvania:s"],
    Border "north_carolina:s" "nc" ["virginia:s", "south_carolina:s", "georgia:s", "tennessee:s"],
    Border "north_dakota:s" "nd" ["minnesota:s", "south_dakota:s", "montana:s"],
    Border "ohio:s" "oh" ["michigan:s", "pennsylvania:s", "west_virginia:s", "kentucky:s", "indiana:s"],
    Border "oklahoma:s" "ok" ["kansas:s", "missouri:s", "arkansas:s", "texas:s", "new_mexico:s", "colorado:s"],
    Border "oregon:s" "or" ["washington:s", "idaho:s", "nevada:s", "california:s"],
    Border "pennsylvania:s" "pa" ["new_york:s", "new_jersey:s", "delaware:s", "maryland:s", "west_virginia:s", "ohio:s"],
    Border "rhode_island:s" "ri" ["massachusetts:s", "connecticut:s"],
    Border "south_carolina:s" "sc" ["north_carolina:s", "georgia:s"],
    Border "south_dakota:s" "sd" ["north_dakota:s", "minnesota:s", "iowa:s", "nebraska:s", "wyoming:s", "montana:s"],
    Border "tennessee:s" "tn" ["kentucky:s", "virginia:s", "north_carolina:s", "georgia:s", "alabama:s", "mississippi:s", "arkansas:s", "missouri:s"],
    Border "texas:s" "tx" ["oklahoma:s", "arkansas:s", "louisiana:s", "new_mexico:s"],
    Border "utah:s" "ut" ["wyoming:s", "colorado:s", "new_mexico:s", "arizona:s", "nevada:s", "idaho:s"],
    Border "vermont:s" "vt" ["new_hampshire:s", "massachusetts:s", "new_york:s"],
    Border "virginia:s" "va" ["maryland:s", "district_of_columbia:s", "north_carolina:s", "tennessee:s", "kentucky:s", "west_virginia:s"],
    Border "washington:s" "wa" ["idaho:s", "oregon:s"],
    Border "west_virginia:s" "wv" ["pennsylvania:s", "maryland:s", "virginia:s", "kentucky:s", "ohio:s"],
    Border "wisconsin:s" "wi" ["michigan:s", "illinois:s", "iowa:s", "minnesota:s"],
    Border "wyoming:s" "wy" ["montana:s", "south_dakota:s", "nebraska:s", "colorado:s", "utah:s", "idaho:s"]]


highlows = [HighLow "alabama:s" "al" "cheaha_mountain:p" 734 "gulf_of_mexico:p" 0,
    HighLow "alaska:s" "ak" "mount_mckinley:p" 6194 "pacific_ocean:p" 0,
    HighLow "arizona:s" "az" "humphreys_peak:p" 3851 "colorado_river:p" 21,
    HighLow "arkansas:s" "ar" "magazine_mountain:p" 839 "ouachita_river:p" 17,
    HighLow "california:s" "ca" "mount_whitney:p" 4418 "death_valley:p" (-85),
    HighLow "colorado:s" "co" "mount_elbert:p" 4399 "arkansas_river:p" 1021,
    HighLow "connecticut:s" "ct" "mount_frissell:p" 725 "long_island_sound:p" 0,
    HighLow "delaware:s" "de" "centerville:p" 135 "atlantic_ocean:p" 0,
    HighLow "district_of_columbia:s" "dc" "tenleytown:p" 125 "potomac_river:p" 0,
    HighLow "florida:s" "fl" "walton_county:p" 105 "atlantic_ocean:p" 0,
    HighLow "georgia:s" "ga" "brasstown_bald:p" 1458 "atlantic_ocean:p" 0,
    HighLow "hawaii:s" "hi" "mauna_kea:p" 4205 "pacific_ocean:p" 0,
    HighLow "idaho:s" "id" "borah_peak:p" 3859 "snake_river:p" 216,
    HighLow "illinois:s" "il" "charles_mound:p" 376 "mississippi_river:p" 85,
    HighLow "indiana:s" "in" "franklin_township:p" 383 "ohio_river:p" 98,
    HighLow "iowa:s" "ia" "ocheyedan_mound:p" 511 "mississippi_river:p" 146,
    HighLow "kansas:s" "ks" "mount_sunflower:p" 1231 "verdigris_river:p" 207,
    HighLow "kentucky:s" "ky" "black_mountain:p" 1263 "mississippi_river:p" 78,
    HighLow "louisiana:s" "la" "driskill_mountain:p" 163 "new_orleans:p" (-1),
    HighLow "maine:s" "me" "mount_katahdin:p" 1606 "atlantic_ocean:p" 0,
    HighLow "maryland:s" "md" "backbone_mountain:p" 1024 "atlantic_ocean:p" 0,
    HighLow "massachusetts:s" "ma" "mount_greylock:p" 1064 "atlantic_ocean:p" 0,
    HighLow "michigan:s" "mi" "mount_curwood:p" 604 "lake_erie:p" 174,
    HighLow "minnesota:s" "mn" "eagle_mountain:p" 701 "lake_superior:p" 183,
    HighLow "mississippi:s" "ms" "woodall_mountain:p" 246 "gulf_of_mexico:p" 0,
    HighLow "missouri:s" "mo" "taum_sauk_mountain:p" 540 "st._francis_river:p" 70,
    HighLow "montana:s" "mt" "granite_peak:p" 3901 "kootenai_river:p" 549,
    HighLow "nebraska:s" "ne" "johnson_township:p" 1654 "southeast_corner:p" 256,
    HighLow "nevada:s" "nv" "boundary_peak:p" 4005 "colorado_river:p" 143,
    HighLow "new_hampshire:s" "nh" "mount_washington:p" 1917 "atlantic_ocean:p" 0,
    HighLow "new_jersey:s" "nj" "high_point:p" 550 "atlantic_ocean:p" 0,
    HighLow "new_mexico:s" "nm" "wheeler_peak:p" 4011 "red_bluff_reservoir:p" 859,
    HighLow "new_york:s" "ny" "mount_marcy:p" 1629 "atlantic_ocean:p" 0,
    HighLow "north_carolina:s" "nc" "mount_mitchell:p" 2037 "atlantic_ocean:p" 0,
    HighLow "north_dakota:s" "nd" "white_butte:p" 1069 "red_river:p" 229,
    HighLow "ohio:s" "oh" "campbell_hill:p" 472 "ohio_river:p" 132,
    HighLow "oklahoma:s" "ok" "black_mesa:p" 1516 "little_river:p" 87,
    HighLow "oregon:s" "or" "mount_hood:p" 3424 "pacific_ocean:p" 0,
    HighLow "pennsylvania:s" "pa" "mount_davis:p" 979 "delaware_river:p" 0,
    HighLow "rhode_island:s" "ri" "jerimoth_hill:p" 247 "atlantic_ocean:p" 0,
    HighLow "south_carolina:s" "sc" "sassafras_mountain:p" 1085 "atlantic_ocean:p" 0,
    HighLow "south_dakota:s" "sd" "harney_peak:p" 2207 "big_stone_lake:p" 284,
    HighLow "tennessee:s" "tn" "clingmans_dome:p" 2025 "mississippi_river:p" 55,
    HighLow "texas:s" "tx" "guadalupe_peak:p" 2667 "gulf_of_mexico:p" 0,
    HighLow "utah:s" "ut" "kings_peak:p" 4123 "beaver_dam_creek:p" 610,
    HighLow "vermont:s" "vt" "mount_mansfield:p" 1339 "lake_champlain:p" 29,
    HighLow "virginia:s" "va" "mount_rogers:p" 1746 "atlantic_ocean:p" 0,
    HighLow "washington:s" "wa" "mount_rainier:p" 4392 "pacific_ocean:p" 0,
    HighLow "west_virginia:s" "wv" "spruce_knob:p" 1482 "potomac_river:p" 73,
    HighLow "wisconsin:s" "wi" "timms_hill:p" 595 "lake_michigan:p" 177,
    HighLow "wyoming:s" "wy" "gannett_peak:p" 4202 "belle_fourche_river:p" 945]


mountains = [Mountain "alaska:s" "ak" "mckinley:m" 6194,
    Mountain "alaska:s" "ak" "st._elias:m" 5489,
    Mountain "alaska:s" "ak" "foraker:m" 5304,
    Mountain "alaska:s" "ak" "bona:m" 5044,
    Mountain "alaska:s" "ak" "blackburn:m" 4996,
    Mountain "alaska:s" "ak" "kennedy:m" 4964,
    Mountain "alaska:s" "ak" "sanford:m" 4949,
    Mountain "alaska:s" "ak" "south_buttress:m" 4842,
    Mountain "alaska:s" "ak" "vancouver:m" 4785,
    Mountain "alaska:s" "ak" "churchill:m" 4766,
    Mountain "alaska:s" "ak" "fairweather:m" 4663,
    Mountain "alaska:s" "ak" "hubbard:m" 4577,
    Mountain "alaska:s" "ak" "bear:m" 4520,
    Mountain "alaska:s" "ak" "east_buttress:m" 4490,
    Mountain "alaska:s" "ak" "hunter:m" 4442,
    Mountain "alaska:s" "ak" "alverstone:m" 4439,
    Mountain "alaska:s" "ak" "browne_tower:m" 4429,
    Mountain "california:s" "ca" "whitney:m" 4418,
    Mountain "colorado:s" "co" "elbert:m" 4399,
    Mountain "colorado:s" "co" "massive:m" 4396,
    Mountain "colorado:s" "co" "harvard:m" 4395,
    Mountain "washington:s" "wa" "rainier:m" 4392,
    Mountain "california:s" "ca" "williamson:m" 4382,
    Mountain "colorado:s" "co" "bianca:m" 4372,
    Mountain "colorado:s" "co" "la_plata:m" 4370,
    Mountain "colorado:s" "co" "uncompahgre:m" 4361,
    Mountain "colorado:s" "co" "crestone:m" 4357,
    Mountain "colorado:s" "co" "lincoln:m" 4354,
    Mountain "colorado:s" "co" "grays:m" 4349,
    Mountain "colorado:s" "co" "antero:m" 4349,
    Mountain "colorado:s" "co" "torreys:m" 4349,
    Mountain "colorado:s" "co" "castle:m" 4348,
    Mountain "colorado:s" "co" "quandary:m" 4348,
    Mountain "colorado:s" "co" "evans:m" 4348,
    Mountain "colorado:s" "co" "longs:m" 4345,
    Mountain "colorado:s" "co" "wilson:m" 4342,
    Mountain "california:s" "ca" "white:m" 4342,
    Mountain "california:s" "ca" "north_palisade:m" 4341,
    Mountain "colorado:s" "co" "shavano:m" 4337,
    Mountain "colorado:s" "co" "belford:m" 4327,
    Mountain "colorado:s" "co" "princeton:m" 4327,
    Mountain "colorado:s" "co" "crestone_needle:m" 4327,
    Mountain "colorado:s" "co" "yale:m" 4327,
    Mountain "colorado:s" "co" "bross:m" 4320,
    Mountain "colorado:s" "co" "kit_carson:m" 4317,
    Mountain "alaska:s" "ak" "wrangell:m" 4317,
    Mountain "california:s" "ca" "shasta:m" 4317,
    Mountain "california:s" "ca" "sill:m" 4317,
    Mountain "colorado:s" "co" "el_diente:m" 4316,
    Mountain "colorado:s" "co" "maroon:m" 4315]


roads = [Road "90" ["massachusetts","new york","pennsylvania","ohio","indiana","illinois","wisconsin","minnesota","south dakota","wyoming","montana","idaho","washington"],
    Road "80" ["new york","new jersey","pennsylvania","ohio","indiana","illinois","iowa","nebraska","wyoming","utah","nevada","california"],
    Road "70" ["district of columbia","maryland","pennsylvania","ohio","indiana","illinois","missouri","kansas","colorado","utah"],
    Road "10" ["florida","alabama","mississippi","louisiana","texas","new mexico","arizona","california"],
    Road "40" ["north carolina","tennessee","arkansas","oklahoma","texas","new mexico","arizona","california"],
    Road "15" ["montana","idaho","utah","arizona","nevada","california"],
    Road "20" ["south carolina","georgia","alabama","mississippi","louisiana","texas"],
    Road "35" ["minnesota","iowa","missouri","kansas","oklahoma","texas"],
    Road "55" ["illinois","missouri","arkansas","tennessee","mississippi","louisiana"],
    Road "64" ["virginia","west virginia","kentucky","indiana","illinois","missouri"],
    Road "75" ["michigan","ohio","kentucky","tennessee","georgia","florida"],
    Road "81" ["new york","pennsylvania","maryland","west virginia","virginia","tennessee"],
    Road "77" ["ohio","west virginia","virginia","north carolina","south carolina"],
    Road "85" ["virginia","north carolina","south carolina","georgia","alabama"],
    Road "94" ["illinois","wisconsin","minnesota","north dakota","montana"],
    Road "29" ["north dakota","south dakota","iowa","missouri"],
    Road "65" ["indiana","kentucky","tennessee","alabama"],
    Road "84" ["connecticut","new york","new jersey","pennsylvania"],
    Road "5" ["washington","oregon","california"],
    Road "24" ["tennessee","kentucky","illinois"],
    Road "25" ["wyoming","colorado","new mexico"],
    Road "44" ["missouri","oklahoma","texas"],
    Road "59" ["tennessee","georgia","alabama"],
    Road "74" ["ohio","indiana","illinois"],
    Road "78" ["new york","new jersey","pennsylvania"],
    Road "84" ["utah","idaho","oregon"],
    Road "91" ["vermont","massachusetts","connecticut"],
    Road "93" ["new hampshire","vermont","massachusetts"],
    Road "8" ["arizona","california"],
    Road "30" ["arkansas","texas"],
    Road "57" ["illinois","missouri"],
    Road "66" ["district of columbia","virginia"],
    Road "69" ["michigan","indiana"],
    Road "71" ["ohio","kentucky"],
    Road "76" ["nebraska","colorado"],
    Road "79" ["pennsylvania","west virginia"],
    Road "83" ["pennsylvania","maryland"],
    Road "86" ["massachusetts","connecticut"],
    Road "89" ["vermont","new hampshire"]]

lakes = [Lake "superior:l" 82362 ["michigan:s", "wisconsin:s", "minnesota:s"],
    Lake "huron:l" 59570 ["michigan:s"],
    Lake "michigan:l" 58016 ["michigan:s", "indiana:s", "illinois:s", "wisconsin:s"],
    Lake "erie:l" 25667 ["new_york:s", "pennsylvania:s", "ohio:s", "michigan:s"],
    Lake "ontario:l" 19684 ["new_york:s"],
    Lake "great_salt_lake:l" 5180 ["utah:s"],
    Lake "lake_of_the_woods:l" 4391 ["minnesota:s"],
    Lake "iliamna:l" 2675 ["alaska:s"],
    Lake "okeechobee:l" 1810 ["florida:s"],
    Lake "pontchartrain:l" 1632 ["louisiana:s"],
    Lake "becharof:l" 1186 ["alaska:s"],
    Lake "red:l" 1169 ["minnesota:s"],
    Lake "st._clair:l" 1119 ["michigan:s"],
    Lake "champlain:l" 1114 ["vermont:s", "new_york:s"],
    Lake "rainy:l" 932 ["minnesota:s"],
    Lake "salton_sea:l" 932 ["california:s"],
    Lake "teshekpuk:l" 816 ["alaska:s"],
    Lake "naknek:l" 630 ["alaska:s"],
    Lake "winnebago:l" 557 ["wisconsin:s"],
    Lake "mille_lacs:l" 536 ["minnesota:s"],
    Lake "flathead:l" 510 ["montana:s"],
    Lake "tahoe:l" 497 ["nevada:s", "california:s"]]